CREATE TABLE IF NOT EXISTS usuario (
    cui BIGINT NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    escuela VARCHAR(100),
    rol VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS escuela (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS deporte (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    jugadores INT NOT NULL,
    suplentes INT NOT NULL,
    tipo VARCHAR(100) NOT NULL
);
